### ISSUE TITLE
Throttle adapter probably has a bug in it

### ISSUE THREAD

**Issue by constant-suffering** [teloxide/teloxide-core#120]
It's expected from `Throttle` to guarantee all messages delivery at cost of delays that it makes (or it should make) automatically. However, it delivers only a small part of messages (see MRE). It seems like throttle does not properly wait to send more messages, but sends them right away and so ` RetryAfter(X)` errors are returned. 

I've extracted a MRE from my project which initially worked with images, but the undesired behavior seems to occur when sending text messages as well. 

### main.rs
```rust
use teloxide_core::{
    adaptors::throttle::Limits,
    Bot,
    requests::{Requester, RequesterExt},
    types::ChatId,
};

#[tokio::main()]
async fn main() {
    let bot = Bot::from_env()
        .throttle(Limits::default())
        .auto_send();
    let chat_id = ChatId::ChannelUsername("<@channel-username>".to_owned());
    let iter = (1..100)
        .map(|i| bot.send_message(chat_id.clone(), i.to_string()));
    let res = futures::future::join_all(iter).await;
    println!("results: {:?}", res);
}
```

### Cargo.toml
```toml
[package]
name = "teloxide-throttle-bug-mre"
version = "0.1.0"
edition = "2018"

[dependencies]
teloxide-core = { version = "0.3.3", features = ["auto_send", "throttle"] }
futures = "0.3.16"
tokio = { version = "1.9.0", features = ["rt-multi-thread", "macros"] }
```

---------------------------

### GIF
![Peek 2021-09-15 19-15](https://user-images.githubusercontent.com/54008526/133470615-3d3203cb-ae00-4b87-bb74-2802284c0895.gif)
